/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 01 10:27:39 GMT 2022
 */

package com.siddhu.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.siddhu.aop.SiddhuaopExampleApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SiddhuaopExampleApplication_ESTest extends SiddhuaopExampleApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SiddhuaopExampleApplication siddhuaopExampleApplication0 = new SiddhuaopExampleApplication();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[5];
      // Undeclared exception!
      try { 
        SiddhuaopExampleApplication.main(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No qualifying bean of type 'com.siddhu.aop.siddhucomponent' available
         //
         verifyException("org.springframework.beans.factory.support.DefaultListableBeanFactory", e);
      }
  }
}
