/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 01 10:27:41 GMT 2022
 */

package com.siddhu.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import com.siddhu.aop.siddhuhelperaop;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class siddhuhelperaop_ESTest extends siddhuhelperaop_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      siddhuhelperaop siddhuhelperaop0 = new siddhuhelperaop();
      siddhuhelperaop0.log();
  }
}
