/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 01 10:27:02 GMT 2022
 */

package com.siddhu.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import com.siddhu.aop.siddhucomponent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class siddhucomponent_ESTest extends siddhucomponent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      siddhucomponent siddhucomponent0 = new siddhucomponent();
      siddhucomponent0.showLog();
  }
}
